rubocop.yml
Removed after talk with @ybregey 
Removing the custom configuration will result in falling back to the default one (`AllowAsExpressionSeparator: false`). See [here](https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/LineLength).
=> [~] Remove Style/Semicolon custom configuration

rubocop-rspec.yml, rubocop.yml
1. request tests have empty examples due to rswag DSL.
that why I disabled ```EmptyExampleGroup``` cop for everything what we have in spec/requests directory.
2. changed EndAlignment to ```variable``` which is kinda convention what we had on STS
```ruby
variable = if true
end
variable = if true
end
variable =
if true
end
```
=> [~] tune rubocop

rubocop-rspec.yml
rswag DSL does not follow some RSpec cops by default, so the PR disables two of them:
```ruby
spec/requests/api/v3/internal/rmo_clients_spec.rb:5:1: C: RSpec/MultipleMemoizedHelpers: Example group has too many memoized helpers [6/5]                                                                                                  
RSpec.describe "Api::V3::Internal::RmoClients", type: :request, swagger_doc: "api/v3/internal/swagger.json" do ...                                                                                                                          
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ …
```
=> [~] rspec for request tests

rubocop-rspec.yml
I've been with an eye on our pull requests/codebase and come up with these as more sensible configurations.
RSpec/NestedGroups: raised from 5 to 6.
RSpec/MessageSpies: prefer using `expect(obj).to receive(:method)` instead of `expect(obj).to have_received`.
RSpec/ExampleLength: raised from 5 to 30.
RSpec/MultipleMemoizedHelpers: allow up to 10 `let`s on an example (raised from 5).
=> [~] Add more sensible rubocop configurations

rubocop-rails.yml, rubocop-rspec.yml, rubocop.yml
Rails/ReversibleMigration: disabled as we do not support db:rollback anyway
Style/Documentation: disabled on migrations
=> [~] Sensible rails configurations

rubocop.yml
Add `Layout/CaseIndentation: { EnforcedStyle: "end" }` to match our other rules.
Also reorder cops alphabetically.
```ruby
a = case n
when 0
x * 2
else
y / 3
end
a = case n
in pattern
x * 2
else
y / 3
end
a = case n
when 0
x * 2
else
y / 3
end
a = case n
in pattern
x * 2
else
y / 3
end
```
=> [~] Add proper Layout/CaseIndentation rule

rubocop.yml
Following discussions on Slack, disabled these two cops on test files:
https://www.rubydoc.info/github/bbatsov/RuboCop/RuboCop/Cop/Layout/FirstMethodArgumentLineBreak
https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Layout/MultilineMethodCallBraceLayout
=> Disable some multiline block cops in tests

rubocop.yml
`annotated` style (before):
```
format('%{greeting}', greeting: 'Hello')
format('%s', 'Hello')
format('%<greeting>s', greeting: 'Hello')
```
`template` style (after):
```
format('%<greeting>s', greeting: 'Hello')
format('%s', 'Hello')
format('%{greeting}', greeting: 'Hello')
```
* On `overhaul-backend` we already have 390+ offenses if configured using `annotated` (the default configuration), which lead rubocop to create an entry to `.rubocop_todo` editing its configuration to `template` (this change has no effect to `overhaul-backend`)
* On `notification-management-new` we already use `template` (configured on its .rubocop.yml) (this change has no effect to `notification-management-new`)
=> Change Style/FormatStringToken style to template

rubocop-rspec.yml, rubocop.yml
This PR aims to make examples more consistent and to enforce example messages presence *unless* the test is a one-liner.
Before this PR, those examples are fine:
```ruby
it {
expect(something).to be_true
expect(other_something).to be_true
}
it do
expect(something).to be_true
expect(other_something).to be_true
end
```
After this PR, those example have to be written as:
```ruby
it "does something" do
expect(something).to be_true
expect(other_something).to be_true
end
it { expect(something).to be_true }
```
=> Improve rspec messages

rubocop.yml
Change configuration on cop that checks for string literals inside interpolations
See: https://www.rubydoc.info/gems/rubocop/RuboCop/Cop/Style/StringLiteralsInInterpolation
Before:
```ruby
"Hello #{%w[foo bar].join(", ")}"
<<~STR
Hello #{%w[foo bar].join(", ")}
STR
"Hello #{%w[foo bar].join(', ')}"
<<~STR
Hello #{%w[foo bar].join(', ')}
STR
```
After:
```ruby
"Hello #{%w[foo bar].join(', ')}"
<<~STR
Hello #{%w[foo bar].join(', ')}
STR
"Hello #{%w[foo bar].join(", ")}"
<<~STR
Hello #{%w[foo bar].join(", ")}
STR
```
=> [~] Add style for StringLiteralsInInterpolation

rubocop.yml
Disable on routes definitions, otherwise it complains with:
```ruby
namespace :v2 do
...
end
```
=> Disable Naming/VariableNumber on routes.rb

rubocop.yml
When updating rubocop_todo, noticed that a good amount of files were being added to exclude.
Based on some discussion, it would make sense to disable it for now.
https://over-haul.atlassian.net/browse/P20-713
=> Disable Style/Documentation

rubocop-rspec.yml, rubocop-rswag.yml
The creation of `rubocop-rswag.yml` is a workaround to fix the issue of rubocop not merging excluded files of department with excluded at cop level.
Given the following config:
```yml
RSpec:
Exclude:
- "spec/requests/**/*.rb"
```
And:
```yml
RSpec/LetSetup:
Exclude:
- "spec/api/controllers/create_spec.rb"
```
The `LetSetup` exclusion will not be applied to `/request/**/*.rb` tests and `RSpec/LetSetup` offenses will be seen
for requests tests. So, this file ignores all rspec offenses for all requests tests at cop level, because the
Exclude merge works well at this level.
https://over-haul.atlassian.net/browse/P20-713
=> [P20-713] Add rubocop-rswag.yml to exclude the request tests at cop level

rubocop.yml
Before:
```ruby
['hello', 'world'].map { |s| s.upcase }
association :assets, blueprint: Vehicle, view: :full do |workflow|
workflow.assets
end
['hello', 'world'].map(&:upcase)
association :assets, blueprint: Vehicle, view: :full, &:assets
```
After:
```ruby
['hello', 'world'].map { |s| s.upcase }
association :assets, blueprint: Vehicle, view: :full do |workflow|
workflow.assets
end
['hello', 'world'].map(&:upcase)
association :assets, blueprint: Vehicle, view: :full, &:assets
```
=> Change SymbolProc cop style to AllowMethodsWithArguments

rubocop.yml
While updating rubocop_todo, I've noticed that overhaul-backend was taking too long to start analysing the files.
The reason was because the `public/upload` had a huge number of subfolder and files.
I think this issue won't happen on CI, but could happen on dev environment. 
[OH BE] Not excluding public folder:
```
4210 files inspected, 63 offenses detected, 63 offenses auto-correctable
bundle exec rubocop --cache false  364.12s user 67.77s system 80% cpu 8:56.46 total
```
[OH BE] Excluding public folder:
```
4210 files inspected, 63 offenses detected, 63 offenses auto-correctable
bundle exec rubocop --cache false  241.48s user 4.54s system 90% cpu 4:33.30 total
```
=> Exclude public folder

rubocop.yml
Ignore BlockLength on Gemfile as it is not usual for some blocks to have many lines on the Gemfile
=> Ignore BlockLength cop on Gemfile

README.md
Gem was not released, so it can't be installed unless via `github`.
=> Update README - fix Gemfile instructions

rubocop.yml
As discussed on Slack, we have no plans to adopt to the new Ruby 3.1 shorthand Hash syntax.
As the new syntax is a default on rubocop (see https://github.com/rubocop/rubocop/commit/d85a3c496e0077b2fafa4862937ff472015e094e), we have to opt out of it on this gem.
=> Opt out of Ruby 3.1 shorthand Hash syntax

rubocop.yml
This is a duplicate of #30 
oh lord
=> Revert "Opt out of Ruby 3.1 shorthand Hash syntax"

rubocop.yml
Disabling the cop following to a Slack discussion on 22/Sep
---
Cop documentation: https://docs.rubocop.org/rubocop/cops_naming.html#namingblockforwarding
=> Disable anonymous block syntax cop

rubocop-rswag.yml
[2.24.0](https://github.com/rubocop/rubocop-rspec/blob/master/CHANGELOG.md#2240-2023-09-08)
> Split RSpec/FilePath into RSpec/SpecFilePathSuffix and RSpec/SpecFilePathFormat. RSpec/FilePath cop is enabled by default, the two new cops are pending and need to be enabled explicitly. ([@ydah](https://github.com/ydah))
Fixes this error:
```
/home/runner/work/some-repo/some-repo/vendor/bundle/ruby/3.2.0/gems/rubocop-1.56.3/lib/rubocop/config_obsoletion.rb:43:in `reject_obsolete!': The `RSpec/FilePath` cop has been split into `RSpec/SpecFilePathFormat` and `RSpec/SpecFilePathSuffix`. (RuboCop::ValidationError)
(obsolete configuration found in vendor/bundle/ruby/3.2.0/bundler/gems/rubocop-overhaul-71d84a6db110/rubocop-rswag.yml, please update it)
```
=> Fix config change on rubocop-rspec 2.24.0

config/default.yml, lib/rubocop/cop/overhaul/mutable_reform_defaults.rb, lib/rubocop/cop/overhaul_cops.rb, spec/rubocop/cop/overhaul/mutable_reform_defaults_spec.rb
Add new cop that checks whether a Reform property default isn't a mutable object or a callable object. Implementation is somewhat based on the [MutableConstant](https://docs.rubocop.org/rubocop/cops_style.html#stylemutableconstant) cop (strict mode).
```ruby
class Create < Reform::Form
property :name, default: []
end
class Create < Reform::Form
property :name, default: {}
end
class Create < Reform::Form
property :name, default: "foo"
end
class Create < Reform::Form
property :name, default: "foo"
end
class Create < Reform::Form
property :is_good, default: true
end
class Create < Reform::Form
property :name, default: ->{ [] }
end
class Create < Reform::Form
property :name, default: :my_method
def my_method
[]
end
end
```
=> [OK-34681] Add cop MutableReformDefaults

config/default.yml, lib/rubocop/cop/overhaul/assignment_instead_of_comparison.rb, lib/rubocop/cop/overhaul_cops.rb, spec/rubocop/cop/overhaul/assignment_instead_of_comparison_spec.rb
Adds new Rubocop cop that should be able to find a common mistake:
```ruby
my_array.select { |x| x = 4 }
my_array.select { |x| x == 4 }
```
=> [OK-34681] Add cop AssignmentInsteadOfComparison

.github/workflows/publish_gem.yml
NOTE: This workflow has a **manual** trigger. To release new versions, one should manually bump the version (in version.rb), merge their PR to master and manually trigger the workflow (under the [actions](https://github.com/Over-haul/rubocop-overhaul/actions) page).
=> [OK-23600] Add workflow to publish gem

lib/rubocop/cop/overhaul/assignment_instead_of_comparison.rb, lib/rubocop/overhaul/version.rb, spec/rubocop/cop/overhaul/assignment_instead_of_comparison_spec.rb
Also work on setter methods:
```ruby
my_arr.select { |x| x.type = 3 }
my_arr.select { |x| x.type == 3 }
```
=> Fix AssignmentInsteadComparison for setter methods

config/default.yml, lib/rubocop/cop/overhaul/semantic_logger_contract.rb, lib/rubocop/cop/overhaul_cops.rb, spec/rubocop/cop/overhaul/semantic_logger_contract_spec.rb
Checks for a logger usage that is compatible with SemanticLogger. For context, using the `payload:` keyword along with non-supported keywords raises an error in runtime in SemanticLogger, see: https://github.com/reidmorrison/semantic_logger/discussions/265
```ruby
logger.info(message: "foo", payload: {}, error: StandardError.new)
logger.info(message: "foo", error: StandardError.new)
logger.info(message: "foo", payload: {}, exception: StandardError.new)
logger.info("foo", {}, StandardError.new)
```
(note: although enabled by default, this cop is specific to [SemanticLogger](https://github.com/reidmorrison/semantic_logger/))
=> [OK-38947] New cop: Overhaul/SemanticLoggerContract cop

.github/CODEOWNERS
As discussed in the last retro, setup CODEOWNERS such as:
- for sensitive bits of architecture (changes to  database, http routes & kafka consumers), require a code review from [be-core](https://github.com/orgs/Over-haul/teams/be-core)
- for everything else, require a code view from any ruby developer in [overhaul-ruby-dev-team](https://github.com/orgs/Over-haul/teams/overhaul-ruby-dev-team)
=> [OK-42561] CODEOWNERS: use `overhaul-ruby-dev-team` instead of `be-core`

oh_defaults/rubocop-rails.yml
It conflicts with strong_migrations suggestions. For instance, the
following code reports an offense:
```ruby
add_column :foo, :bar, :string
add_column :foo, :baz, :string
```
The above is suggested to be written instead as:
```ruby
change_table :foo, bulk: true do |t|
t.string :bar
t.string :baz
end
```
Which in turn is not supported with strong_migrations and raises an
error when trying to execute the migration:
https://github.com/ankane/strong_migrations?tab=readme-ov-file#assuring-safety
> Certain methods like execute and **change_table** cannot be inspected and
> are prevented from running by default. Make sure what you’re doing is
> really safe and use this pattern.
=> [~] Disable `Rails/BulkChangeTable` as it conflicts with strong_migrations

lib/rubocop/overhaul/version.rb, oh_defaults/rubocop-factory_bot.yml, oh_defaults/rubocop-rspec.yml
* Relax `RSpec/DescribedClass`, disabling it in spec/models/**/*
* as agreed in Slack, allowing usage of explicit class name should make testing model scopes less of a hassle
* Workaround for FactoryBot/AssociationStyle false positive
The following code was raising a warning where it shouldn't:
```ruby
FactoryBot.define do
factory :user do
name { "John" }
trait :john
end
end
```
=> Relax config for rubocop-rspec and add workaround for factory_bot false positive
